# Application name
spring:
  application:
    name: UserService

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  # Optional: Additional Spring Data JPA settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Server configuration
server:
  port: 8081
